version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: fs
      MYSQL_USER: fs
      MYSQL_PASSWORD: calgary
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: "redis:3-alpine"
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redis_data:/data

  web:
    image: melonfacedoom/flask_scraper:latest
    restart: always
    command: venv/bin/celery worker -A fs.celery --loglevel=info
    depends_on:
      - db
      - redis
    ports:
      - 8000:5000
    links:
      - db
    environment:
      SECRET_KEY: "my-secret-key"
      DATABASE_URL: mysql+pymysql://fs:calgary@db/fs?charset=utf8mb4
      REDIS_URL: "redis://redis:6379"


  celery:
    image: melonfacedoom/flask_scraper:latest
    restart: always
    entrypoint: venv/bin/celery
    command: worker -A fs.celery --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: "my-secret-key"
      DATABASE_URL: mysql+pymysql://fs:calgary@db/fs?charset=utf8mb4
      REDIS_URL: "redis://redis:6379"
      C_FORCE_ROOT: "true"
    links:
      - redis
      - db

  celery-beat:
    image: melonfacedoom/flask_scraper:latest
    restart: always
    entrypoint: venv/bin/celery
    command: beat -A fs.celery --schedule=/tmp/cerybeat-schedule --loglevel=INFO --pidfile=/tmp/celerybeat.pid
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: "my-secret-key"
      DATABASE_URL: mysql+pymysql://fs:calgary@db/fs?charset=utf8mb4
      REDIS_URL: "redis://redis:6379"
      C_FORCE_ROOT: "true"
    links:
      - redis
      - db

volumes:
  db_data: {}
  redis_data: {}
