version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: dnms
      MYSQL_USER: dnms
      MYSQL_PASSWORD: calgary
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: "redis:3-alpine"
    ports:
      - 6379:6379
    restart: always

  web:
    image: dnms:latest
    command: venv/bin/celery worker -A DNMS.celery --loglevel=info
    depends_on:
      - db
      - redis
    ports:
      - 8000:5000
    links:
      - db
    environment:
      SECRET_KEY: "my-secret-key"
      DATABASE_URL: mysql+pymysql://dnms:calgary@db/dnms?charset=utf8mb4
      REDIS_URL: "redis://redis:6379"


  celery:
    image: dnms:latest
    entrypoint: venv/bin/celery
    command: worker -A DNMS.celery --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: "my-secret-key"
      DATABASE_URL: mysql+pymysql://dnms:calgary@db/dnms?charset=utf8mb4
      REDIS_URL: "redis://redis:6379"
      C_FORCE_ROOT: "true"
    links:
      - redis
      - db

volumes:
  db_data: {}
